# -*- coding: utf-8 -*-
"""Partnership & Revenue Performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WE5PkBH7xbMUoj-ZDJt0xqRMwL5akMnP
"""

import pandas as pd

df = pd.read_excel("partnerships.xlsx")

df["Revenue_per_Deal"] = df["Revenue"] / df["Deals_Closed"]

df["Performance_Score"] = df["Revenue"] * 0.5 + df["Deals_Closed"] * 1000


df["Partner_Rank"] = df["Performance_Score"].rank(ascending=False)


df_sorted = df.sort_values(by="Performance_Score", ascending=False)

print(" Partnership & Revenue Analysis")
print("--------------------------------")
print(df_sorted[[
    "Partner_Name",
    "Region",
    "Revenue",
    "Deals_Closed",
    "Revenue_per_Deal",
    "Performance_Score",
    "Partner_Rank"
]])


top_partner = df_sorted.iloc[0]
print(f"\n Top Partner: {top_partner['Partner_Name']} in {top_partner['Region']} generating ${int(top_partner['Revenue']):,} with {int(top_partner['Deals_Closed'])} deals closed.")


df_sorted.to_csv("cleaned_partnership_data.csv", index=False)
print("\n Cleaned data exported for Tableau visualization.")